name: "aws-eco-runner"
description: "AWS Eco Runner is a solution designed to optimize the cost of using GitHub Actions runners"
author: "NodeSource"

inputs:
  instances_id:
    description: "Array with ID of the EC2 instance to start OR stop"
    required: true
  action:
    description: "Define if I want to start or stop the runner"
    required: true
    default: "start"

runs:
  using: "node20"
  main: "dist/index.js"
  post-if: success()

branding:
  icon: "award"
  color: "green"
